# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-07 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=500, null=True)),
                ('password', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('addtime', models.CharField(default='', max_length=500, null=True)),
                ('content', models.CharField(default='', max_length=500, null=True)),
                ('team', models.CharField(default='', max_length=500, null=True)),
                ('teamid', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(default='', max_length=500, null=True)),
                ('teamid', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('state', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500, null=True)),
                ('addtime', models.CharField(default='', max_length=500, null=True)),
                ('content', models.CharField(default='', max_length=500, null=True)),
                ('biaoqian1', models.CharField(default='', max_length=500, null=True)),
                ('biaoqian2', models.CharField(default='', max_length=500, null=True)),
                ('biaoqian3', models.CharField(default='', max_length=500, null=True)),
                ('biaoqian4', models.CharField(default='', max_length=500, null=True)),
                ('tfidfci1', models.CharField(default='', max_length=500, null=True)),
                ('tfidfci2', models.CharField(default='', max_length=500, null=True)),
                ('tfidfci3', models.CharField(default='', max_length=500, null=True)),
                ('tfidfci4', models.CharField(default='', max_length=500, null=True)),
                ('kmeansci1', models.CharField(default='', max_length=500, null=True)),
                ('kmeansci2', models.CharField(default='', max_length=500, null=True)),
                ('kmeansci3', models.CharField(default='', max_length=500, null=True)),
                ('kmeansci4', models.CharField(default='', max_length=500, null=True)),
                ('jurisdiction', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('state', models.CharField(default='', max_length=500, null=True)),
                ('file', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('introduce', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teammembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(default='', max_length=500, null=True)),
                ('teamid', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teamnotice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500, null=True)),
                ('addtime', models.CharField(default='', max_length=500, null=True)),
                ('content', models.CharField(default='', max_length=500, null=True)),
                ('team', models.CharField(default='', max_length=500, null=True)),
                ('teamid', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('realname', models.CharField(default='', max_length=500, null=True)),
                ('username', models.CharField(default='', max_length=500, null=True)),
                ('password', models.CharField(default='', max_length=500, null=True)),
                ('sex', models.CharField(default='', max_length=500, null=True)),
                ('age', models.CharField(default='', max_length=500, null=True)),
                ('introduce', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
    ]
